{% set name = "opentelemetry-instrumentation-pymysql" %}
{% set version = "0.41b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_pymysql-{{ version }}.tar.gz
  sha256: ecf129dc51666a2b340a3209a4b7a14efb21dd83f5cd91b73aaaa054b15d3d0a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation-dbapi ==0.41b0
    - opentelemetry-instrumentation ==0.41b0
    # - pymysql <2
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-pymysql 


test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-pymysql
  summary: OpenTelemetry PyMySQL instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
